[project]
name = "web3py-simple-storage-cu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["python-dotenv>=1.0.1", "vyper>=0.4.1", "web3>=7.2.0"]
